#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : CUnit
Version  : 2.1.3
Release  : 15
URL      : https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2
Source0  : https://sourceforge.net/projects/cunit/files/CUnit/2.1-3/CUnit-2.1-3.tar.bz2
Summary  : A unit testing framework for 'C'
Group    : Development/Tools
License  : LGPL-2.0
Requires: CUnit-data = %{version}-%{release}
Requires: CUnit-lib = %{version}-%{release}
Requires: CUnit-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
CUnit is a unit testing framework for C.
This package installs the CUnit static library,
headers, and documentation files.

%package data
Summary: data components for the CUnit package.
Group: Data

%description data
data components for the CUnit package.


%package dev
Summary: dev components for the CUnit package.
Group: Development
Requires: CUnit-lib = %{version}-%{release}
Requires: CUnit-data = %{version}-%{release}
Provides: CUnit-devel = %{version}-%{release}
Requires: CUnit = %{version}-%{release}

%description dev
dev components for the CUnit package.


%package dev32
Summary: dev32 components for the CUnit package.
Group: Default
Requires: CUnit-lib32 = %{version}-%{release}
Requires: CUnit-data = %{version}-%{release}
Requires: CUnit-dev = %{version}-%{release}

%description dev32
dev32 components for the CUnit package.


%package lib
Summary: lib components for the CUnit package.
Group: Libraries
Requires: CUnit-data = %{version}-%{release}
Requires: CUnit-license = %{version}-%{release}

%description lib
lib components for the CUnit package.


%package lib32
Summary: lib32 components for the CUnit package.
Group: Default
Requires: CUnit-data = %{version}-%{release}
Requires: CUnit-license = %{version}-%{release}

%description lib32
lib32 components for the CUnit package.


%package license
Summary: license components for the CUnit package.
Group: Default

%description license
license components for the CUnit package.


%prep
%setup -q -n CUnit-2.1-3
pushd ..
cp -a CUnit-2.1-3 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569524365
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%reconfigure --disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1569524365
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/CUnit
cp COPYING %{buildroot}/usr/share/package-licenses/CUnit/COPYING
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)
/usr/doc/CUnit/CUnit_doc.css
/usr/doc/CUnit/error_handling.html
/usr/doc/CUnit/fdl.html
/usr/doc/CUnit/headers/Automated.h
/usr/doc/CUnit/headers/Basic.h
/usr/doc/CUnit/headers/CUCurses.h
/usr/doc/CUnit/headers/CUError.h
/usr/doc/CUnit/headers/CUnit.h
/usr/doc/CUnit/headers/CUnit_intl.h
/usr/doc/CUnit/headers/Console.h
/usr/doc/CUnit/headers/MyMem.h
/usr/doc/CUnit/headers/TestDB.h
/usr/doc/CUnit/headers/TestRun.h
/usr/doc/CUnit/headers/Util.h
/usr/doc/CUnit/headers/Win.h
/usr/doc/CUnit/index.html
/usr/doc/CUnit/introduction.html
/usr/doc/CUnit/managing_tests.html
/usr/doc/CUnit/running_tests.html
/usr/doc/CUnit/test_registry.html
/usr/doc/CUnit/writing_tests.html

%files data
%defattr(-,root,root,-)
/usr/share/CUnit/CUnit-List.dtd
/usr/share/CUnit/CUnit-List.xsl
/usr/share/CUnit/CUnit-Run.dtd
/usr/share/CUnit/CUnit-Run.xsl
/usr/share/CUnit/Memory-Dump.dtd
/usr/share/CUnit/Memory-Dump.xsl

%files dev
%defattr(-,root,root,-)
/usr/include/CUnit/Automated.h
/usr/include/CUnit/Basic.h
/usr/include/CUnit/CUError.h
/usr/include/CUnit/CUnit.h
/usr/include/CUnit/CUnit_intl.h
/usr/include/CUnit/Console.h
/usr/include/CUnit/MyMem.h
/usr/include/CUnit/TestDB.h
/usr/include/CUnit/TestRun.h
/usr/include/CUnit/Util.h
/usr/lib64/libcunit.so
/usr/lib64/pkgconfig/cunit.pc
/usr/share/man/man3/CUnit.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libcunit.so
/usr/lib32/pkgconfig/32cunit.pc
/usr/lib32/pkgconfig/cunit.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcunit.so.1
/usr/lib64/libcunit.so.1.0.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libcunit.so.1
/usr/lib32/libcunit.so.1.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/CUnit/COPYING
