#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : CUnit
Version  : 2.1
Release  : 3
URL      : http://downloads.sourceforge.net/cunit/CUnit-2.1-3.tar.bz2
Source0  : http://downloads.sourceforge.net/cunit/CUnit-2.1-3.tar.bz2
Summary  : A unit testing framework for 'C'
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: CUnit-lib
Requires: CUnit-data
Requires: CUnit-doc

%description
CUnit is a unit testing framework for C.
This package installs the CUnit static library,
headers, and documentation files.

%package data
Summary: data components for the CUnit package.
Group: Data

%description data
data components for the CUnit package.


%package dev
Summary: dev components for the CUnit package.
Group: Development
Requires: CUnit-lib
Requires: CUnit-data

%description dev
dev components for the CUnit package.


%package doc
Summary: doc components for the CUnit package.
Group: Documentation

%description doc
doc components for the CUnit package.


%package lib
Summary: lib components for the CUnit package.
Group: Libraries
Requires: CUnit-data

%description lib
lib components for the CUnit package.


%prep
%setup -q -n CUnit-2.1-3

%build
%reconfigure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/doc/CUnit/CUnit_doc.css
/usr/doc/CUnit/error_handling.html
/usr/doc/CUnit/fdl.html
/usr/doc/CUnit/headers/Automated.h
/usr/doc/CUnit/headers/Basic.h
/usr/doc/CUnit/headers/CUCurses.h
/usr/doc/CUnit/headers/CUError.h
/usr/doc/CUnit/headers/CUnit.h
/usr/doc/CUnit/headers/CUnit_intl.h
/usr/doc/CUnit/headers/Console.h
/usr/doc/CUnit/headers/MyMem.h
/usr/doc/CUnit/headers/TestDB.h
/usr/doc/CUnit/headers/TestRun.h
/usr/doc/CUnit/headers/Util.h
/usr/doc/CUnit/headers/Win.h
/usr/doc/CUnit/index.html
/usr/doc/CUnit/introduction.html
/usr/doc/CUnit/managing_tests.html
/usr/doc/CUnit/running_tests.html
/usr/doc/CUnit/test_registry.html
/usr/doc/CUnit/writing_tests.html

%files data
%defattr(-,root,root,-)
/usr/share/CUnit/CUnit-List.dtd
/usr/share/CUnit/CUnit-List.xsl
/usr/share/CUnit/CUnit-Run.dtd
/usr/share/CUnit/CUnit-Run.xsl
/usr/share/CUnit/Memory-Dump.dtd
/usr/share/CUnit/Memory-Dump.xsl

%files dev
%defattr(-,root,root,-)
/usr/include/CUnit/Automated.h
/usr/include/CUnit/Basic.h
/usr/include/CUnit/CUError.h
/usr/include/CUnit/CUnit.h
/usr/include/CUnit/CUnit_intl.h
/usr/include/CUnit/Console.h
/usr/include/CUnit/MyMem.h
/usr/include/CUnit/TestDB.h
/usr/include/CUnit/TestRun.h
/usr/include/CUnit/Util.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
